### ISSUE TITLE
Bug Report: 17.0 image missing llvmjit.so

### ISSUE THREAD

**Issue by baarkerlounger** [CircleCI-Public/cimg-postgres#129]
`cimg/postgres:17.0` is missing `llvmjit.so`

---

**Describe the bug**
`cimg/postgres:17.0` does not work with `psycopg2` due to missing llvmjit shared object file:

```
sqlalchemy.exc.OperationalError: (psycopg2.errors.UndefinedFile) could not load library "/usr/lib/postgresql/17/lib/llvmjit.so": libLLVM-14.so.1: cannot open shared object file: No such file or directory
```

The same config works fine on `cimg/postgres:16.4`

**To Reproduce**
[Please provide steps to reproduce the behavior, such as a sample job or config file.](https://github.com/uktrade/company-matching-service/blob/llvmjit_reproducer/.circleci/config.yml)

**Comment by wilbrdt** [comment]
I'm having the same issue with `cimg/postgres:17.0` when complex queries trigger a JIT compilation in PostgreSQL:
```
django.db.utils.OperationalError: could not load library "/usr/lib/postgresql/17/lib/llvmjit.so": libLLVM-14.so.1: cannot open shared object file: No such file or directory
```
The `libllvm14` package is missing, which is required for the JIT functionnality.
It seems that the dependency is lost when the newly added `build-essential` package is purged. I can propose a fix.
