### ISSUE TITLE
PostGIS.control is unavailable

### ISSUE THREAD

**Issue by brodziakm** [CircleCI-Public/cimg-postgres#13]
See original issue #6 

We are still unable to migrate to the new cimg/postgres (postgis variant). Our build fails with the following:

```
SQL State  : 58P01
Error Code : 0
Message    : ERROR: could not open extension control file "/usr/lib/postgresql/13/share/extension/btree_gist.control": No such file or directory
```

Whilst postgis might be in the variant, postgis.control seems to not be installed.

**Comment by felicianotech** [comment]
This isn't a PostGIS issue but rather a `btree_gist.control` issue. This is the same issue as #11 so I am closing in favor of that. Please see #11 for updates... (it's being addressed shortly, new images will be available today).
