### ISSUE TITLE
PostgreSQL Contrib extension uuid-ossp is not available

### ISSUE THREAD

**Issue by brodziakm** [CircleCI-Public/cimg-postgres#16]
Thanks for resolving #11.

https://github.com/CircleCI-Public/cimg-postgres/issues/11#issuecomment-959794008:
> Images have been updated to include extensions that are part of the PostgreSQL Contrib package.
>
> Can people confirm on your end that the errors went away?

I can confirm that I am getting something different, but it doesn't appear to have entirely resolved the problem. We are now getting the following in our build pipelines:

```
SQL State  : 58P01
Error Code : 0
Message    : ERROR: could not open extension control file "/usr/lib/postgresql/13/share/extension/uuid-ossp.control": No such file or directory
Statement  : create extension "uuid-ossp"
```

and in the Postgres image container output, the corresponding:
```
2021-11-04 02:19:51.485 UTC [1407] ERROR:  could not open extension control file "/usr/lib/postgresql/13/share/extension/uuid-ossp.control": No such file or directory
2021-11-04 02:19:51.485 UTC [1407] STATEMENT:  create extension "uuid-ossp"
```

**Comment by brodziakm** [comment]
For reference, it looks like uuid-ossp might need special configuration, as mentioned in https://www.postgresql.org/docs/13/uuid-ossp.html#id-1.11.7.53.6

**Comment by edeesis** [comment]
This is blocking us from migrating from the old circleci/postgres-ram images.

**Comment by schuyler** [comment]
Bump. We just tried upgrading to `cimg-postgres` and experienced the same issue.

**Comment by exactlyaron** [comment]
Same errors for `cimg/postgres:13.4-postgis` / `cimg/postgres:13.3-postgis` when trying to migrate from `circleci/postgres:13.2-postgis-ram`.

**Comment by Wobbley** [comment]
I think this is affecting all images, getting same error on 11.3

**Comment by schuyler** [comment]
@felicianotech: Is this something that's likely to receive attention from CircleCI?

**Comment by felicianotech** [comment]
@schuyler yes

---

Thank to you everyone that has reported. This will be looked into and hopefully resolved by the beginning of the next work week at the latest.

**Comment by felicianotech** [comment]
Hey everyone. I made some changed to include `uuid-ossp` however before I respin all images, I wanted to verify that it's solving the problem.

Only the image tags`cimg/postgres:13.4` and `cimg/postgres:13.4-postgis` have been updated. Can someone who's using that image, or can try it out, confirm that the extension is available? If so, I can then continue to roll it out to the other tags.

cc @exactlyaron since you mentioned this version specifically.

**Comment by texpert** [comment]
> Hey everyone. I made some changed to include `uuid-ossp` however before I respin all images, I wanted to verify that it's solving the problem.
> 
> Only the image tags`cimg/postgres:13.4` and `cimg/postgres:13.4-postgis` have been updated. Can someone who's using that image, or can try it out, confirm that the extension is available? If so, I can then continue to roll it out to the other tags.
> 
> cc @exactlyaron since you mentioned this version specifically.

Yes, the cimg/postgres:13.4 has been installed OK with the uuid-ossp extension!

Though, it is giving the `WARNING: POSTGRES_HOST_AUTH_METHOD has been set to "trust"` despite of specified POSTGRES_PASSWORD

**Comment by edeesis** [comment]
cimg/postgres:13.4 worked for us as well.

**Comment by felicianotech** [comment]
@texpert That warning is okay. PostgreSQL changed their default password behavior a couple of years ago. We basically undid that due to a large number of CircleCI users not using passwords on our platform. For a test CI database on a CI platform, that's okay. This warning is just due to that setting change.

---

I'm happy things seem to be working now. We actually did another update recently which includes even more extensions. Basically, we're trying to mimic the same compile config options that the official Debian package uses for PostgreSQL. That should provide much more compatibility for more use cases of PG.

**Comment by exactlyaron** [comment]
@felicianotech yeah that's [working](https://app.circleci.com/pipelines/github/wmfs/addressbase-premium-blueprint/1202/workflows/aaadfa34-9be9-4f01-be5b-591b90a9e9a5/jobs/2107).     Thanks very much for getting it sorted so quickly.

**Comment by schuyler** [comment]
Great! Is this working on 11.13 as well?

**Comment by brodziakm** [comment]
I've confirmed that my build pipeline works when I use cimg/postgres:13.4. At least, the migrations pass correctly and most tests run. We have one test failure that may be due to a time bomb or race condition, and we are currently evaluating that.

**Comment by Wobbley** [comment]
> Great! Is this working on 11.13 as well?
> 
> **EDIT:** I can confirm that this problem still exists with the 11.13 image

That's to be expected. He stated that it was only for 13 and 9 until he gets confirmation that it works, and it does work. So hopefully we get it on 11 soon

**Comment by jshow** [comment]
thank you for moving forward on this @felicianotech - we're looking forward for uuid-ossp to work with the 12.7 image

**Comment by schuyler** [comment]
Bumping this issue again as we can't migrate to the next-gen images without it. Thanks!

**Comment by edeesis** [comment]
Even though this issue isn't closed, we got a successful build run on cimg/postgres:11.13. Thanks all.

**Comment by jshow** [comment]
thanks @edeesis , cimg/postgres:12.7 is building 🚀

**Comment by sethhitch** [comment]
We were able to successfully switch to `cimg/postgres:11.13` after this change went in, thanks!

**Comment by brodziakm** [comment]
Thanks all, I'll close this as it seems to be done.
