### ISSUE TITLE
Add major version tags in addition to major.minor

### ISSUE THREAD

**Issue by nirojan** [CircleCI-Public/cimg-postgres#32]
At the moment circle only offers `major.minor` version tags for all Postgres images except for 9.6. It would be good to have the latest minor release to also have its major version as another tag, so you always pull the latest release. For example, `12.9` the latest release as of raising this issue would also have `12` as its tag.

This is useful where you want to always test your code against the latest minor version without having to update references every time there is a new Postgres minor release.

Legacy circle Postgres images were following this convention until they were deprecated. Is there a reason this wasn't carried over to new convenience images?

**Comment by felicianotech** [comment]
Closing. Please see: https://github.com/CircleCI-Public/cimg-postgres/pull/33#issuecomment-996079863
