### ISSUE TITLE
Postgres 11.14 image

### ISSUE THREAD

**Issue by schinery** [CircleCI-Public/cimg-postgres#41]
I'm in the process of switching some `circleci` images to their `cimg` equivalents and one of them is Postgres 11.14, however there doesn't appear to be an image currently available for this. 

Looking at https://github.com/CircleCI-Public/cimg-postgres/pull/30 I can see that 11.4 was added, wonder if this was meant to of been 11.14?

I've taken a stab at generating a PR to add a 11.14 image here - https://github.com/CircleCI-Public/cimg-postgres/pull/40.

**Comment by JalexChen** [comment]
Hey @schinery - closing this out as you submitted a PR and #43 addresses this. Also, it was kind of hard to read so I don't blame you, but #30 added 11.4, not 11.14
