### ISSUE TITLE
Postgres 12.0 image

### ISSUE THREAD

**Issue by nick-at-finix** [CircleCI-Public/cimg-postgres#46]
Similar to #41 , our team is in the process of switching out convenience images and have noticed that there is no 12.0 image. We would like to know if it is possible to add support for this version that includes minor version fixes as well.

**Comment by felicianotech** [comment]
I understand that this is probably too late, apologies, but this is being built now. Assuming no issues, we'll have a 12.0 image in an hour or two.

**Comment by nick-at-finix** [comment]
@felicianotech thanks for the update, but we have updated all images to 13.7 now :) Feel free to close this.
