### ISSUE TITLE
Please release updates for 13.9, 14.6, and 15.1

### ISSUE THREAD

**Issue by brycethornton** [CircleCI-Public/cimg-postgres#60]
These were released on November 10th, 2022. Is there a reason new PG releases take so long to get new CircleCI images released? I'm thankful for the work you do I just want to mention that it's important for many of us to get these out the door and not having our CI platform updated makes it much riskier.

**Comment by felicianotech** [comment]
No good reason.

1. I will get a PR ready now for some new versions.
2. I will speak with the team this week about getting these done faster. We aim for < 48 hours for these releases across `cimg` and clearly we're not meeting that mark for this particular image.

**Comment by brycethornton** [comment]
@felicianotech Thank you!

**Comment by brycethornton** [comment]
@felicianotech Looks like these have been built and released. Thank you! I'll close this issue.
