### ISSUE TITLE
FATAL:  role $USER does not exist

### ISSUE THREAD

**Issue by kopax-polyconseil** [CircleCI-Public/cimg-postgres#64]
I am trying to run:

```bash
docker run --rm \
   -p 5432:5432 \
  -u ${POSTGRES_USER} \
  --name pc-postgres \
  -e POSTGRES_USER=${POSTGRES_USER} \
  -e POSTGRES_PASSWORD=${POSTGRES_PASSWORD} \
  -e POSTGRES_DB=${POSTGRES_DB} \
  cimg/postgres:12.9-postgis
```

I get the following error:

```bash
 FATAL:  role "postgres" does not exist
```

I tried to run `createuser -s postgres` inside the container as this is what google advise to do:

```bash
postgres@a6961e7bb45f:/home/circleci/project$ createuser -s postgres
createuser: error: could not connect to database template1: FATAL:  role "postgres" does not exist
```

The server crash, any clue what is going on ?

**Comment by BytesGuy** [comment]
@kopax-polyconseil I am unable to reproduce this issue myself. Likely this is stemming from the `-u ${POSTGRES_USER}` flag which is not really required here. Are you receiving the same issue when using this image in CircleCI?

**Comment by kopax-polyconseil** [comment]
Hello, I use the image in github action :) Don't ask why, our ourg sticked to it when decided to use both circle ci and github action.

It is within a runner macos, and if I change `POSTGRES_USER` to `postgres`, error disappear.
