### ISSUE TITLE
Feature Request: Add environment variables to homepage on circleci developer

### ISSUE THREAD

**Issue by shedworth** [CircleCI-Public/cimg-postgres#99]
It would be helpful if the various env vars that can be passed to the container image (POSTGRES_DB, POSTGRES_USER etc) were described on the CCI homepage (https://circleci.com/developer/images/image/cimg/postgres).

**Comment by BytesGuy** [comment]
Hi @shedworth this would be a task for the docs team, please can you open an issue on their repo? https://github.com/circleci/circleci-docs Thanks!
